src/WebUI/Models/Cart.cs
using Domain.Entities;

namespace WebUI.Models
{
    public class Cart
    {
        public Product Product { get; set; }
        public int Quantity { get; set; }
    }
}

src/WebUI/Controllers/CartController.cs
using System.Collections.Generic;
using System.Linq;
using Application.admin;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebUI.Helpers;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class CartController : Controller
    {
        private readonly ProductManager _productManager;

        public CartController(ProductManager productManager)
        {
            _productManager = productManager;
        }
        
        public IActionResult Index()
        {
            var cart = HttpContext.Session.GetObjectFromJson<List<Cart>>("cart");
            ViewBag.Cart = cart;
            if (cart == null) return View();
            foreach (var item in cart)
            {
                ViewBag.Total += item.Product.Price * item.Quantity;
            }
            return View();
        }

        [Route("/cart/cartdetails")]
        public IActionResult GetCartDetails()
        {
            var cart = HttpContext.Session.GetObjectFromJson<List<Cart>>("cart");
            decimal total = 0;
            var count = 0;
            if (cart == null) return Json(new {Success = true, Items = count, Total = total.ToString("#,##0.00")});
            foreach (var item in cart)
            {
                total += item.Product.Price * item.Quantity; 
                count += item.Quantity;
            }
            return Json(new {Success = true,Items = count,Total = total.ToString("#,##0.00")});
            
        }
        
        public IActionResult Decrease(int productId)
        {
            var cart = HttpContext.Session.GetObjectFromJson<List<Cart>>("cart");
            var product = IsExist(productId);
            if (product != -1)
            {
                if (cart[product].Quantity == 1)
                {
                    Remove(productId);
                    return RedirectToAction(nameof(Index));
                }
                cart[product].Quantity--;
            }
            HttpContext.Session.SetObjectAsJson("cart",cart);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Route("/cart/add/")]
        public IActionResult Add(int productId)
        {
            List<Cart> cart;
            decimal total = 0;
            int count = 0;
            if (HttpContext.Session.GetObjectFromJson<List<Cart>>("cart") == null)
            {
                cart = new List<Cart> {new() {Product = _productManager.GetProductById(productId),Quantity = 1}};
                HttpContext.Session.SetObjectAsJson("cart",cart);
                HttpContext.Session.SetInt32("count",cart.Count);
            }
            else
            {
                cart = HttpContext.Session.GetObjectFromJson<List<Cart>>("cart");
                var index = IsExist(productId);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new Cart{Product = _productManager.GetProductById(productId),Quantity = 1});
                }
                HttpContext.Session.SetObjectAsJson("cart",cart);
                HttpContext.Session.SetInt32("count",cart.Count);
            }
            foreach (var item in cart)
            {
                total += item.Product.Price * item.Quantity;
                count += item.Quantity;
            }
            return Json(new {Success = true,Items = count,Total = total.ToString("#,##0.00")});
        }
        
        [Route("remove/{id:int}")]
        public IActionResult Remove(int id)
        {
            var cart = HttpContext.Session.GetObjectFromJson<List<Cart>>("cart");
            var index = IsExist(id);
            cart.RemoveAt(index);
            HttpContext.Session.SetObjectAsJson("cart", cart);
            HttpContext.Session.SetInt32("count",cart.Count);
            return RedirectToAction("Index");
        }

        private int IsExist(int id)
        {
            var cart = HttpContext.Session.GetObjectFromJson<List<Cart>>("cart");
            for (var i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.ProductId.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }

        [HttpGet]
        public IActionResult Clear()
        {
            HttpContext.Session.SetObjectAsJson("cart",null);
            return View("Index");
        }
    }
}

src/WebUI/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Application.client;
using Domain.Entities;
using Domain.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebUI.Helpers;
using WebUI.Models;
using AccountManager = Application.client.AccountManager;

namespace WebUI.Controllers
{
    [Authorize]
    public class CheckoutController : Controller
    {
        private readonly AccountManager _accountManager;
        private readonly OrderService _orderService;

        public CheckoutController(AccountManager accountManager,
            OrderService orderService)
        {
            _accountManager = accountManager;
            _orderService = orderService;
        }
        
        public IActionResult Index()
        {
            if (HttpContext.Session.GetObjectFromJson<List<Cart>>("cart") == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var customer = _accountManager.GetCustomerById(Convert.ToInt32(User.Claims.ElementAt(1).Value));
            ViewBag.Customer = customer;
            return View();
        }
        
        [HttpPost]
        public IActionResult ProcessOrder(Order model)
        {
            var cart = HttpContext.Session.GetObjectFromJson<List<Cart>>("cart");
            if (ModelState.IsValid)
            {
                var order = new Order
                {
                    Customer = _accountManager.GetCustomerById(Convert.ToInt32(User.Claims.ElementAt(1).Value)),
                    OrderDate = DateTime.UtcNow,
                    PaymentStatus = PaymentStatus.Unpaid,
                    PaymentMethod = model.PaymentMethod,
                    Status = (int) OrderStatus.ManualVerificationNeeded,
                    SubTotal = cart.Sum(x=>x.Product.Price * x.Quantity),
                    Total = cart.Sum(x=>x.Product.Price * x.Quantity) + 5,
                    ShipName = model.ShipName,
                    ShipSurname = model.ShipSurname,
                    ShipAddress = model.ShipAddress,
                    ShipCity = model.ShipCity,
                    ShipCountry = model.ShipCountry,
                    ShipPostalCode = model.ShipPostalCode,
                    ShipPhone = model.ShipPhone,
                    OrderNotes = model.OrderNotes,
                    CustomerId = Convert.ToInt32(User.Claims.ElementAt(1).Value)
                };

                var orderDetails = 
                    cart.Select(cartItem =>
                        new OrderDetail {OrderId = _orderService.GetLastOrderId() + 1, 
                            ProductId = cartItem.Product.ProductId, 
                            Price = cartItem.Product.Price, 
                            Quantity = cartItem.Quantity}).ToList();

                if (model.PaymentMethod == PaymentMethod.Card)
                {
                    TempData["checkoutModel"] = JsonConvert.SerializeObject(model);
                    TempData["order"] = JsonConvert.SerializeObject(order);
                    TempData["orderDetails"] = JsonConvert.SerializeObject(orderDetails);
                    return RedirectToAction("Index", "Payment");
                }
            
                var result = _orderService.Insert(order,orderDetails);
                if (result)
                {
                    HttpContext.Session.SetObjectAsJson("cart",null);
                }
                return RedirectToAction(nameof(Confirmation)); 
            }

            return View("Index",model);
        }

        [HttpGet]
        [Route("/order/confirmation")]
        public IActionResult Confirmation(string orderNumber) => View();
    }
}

src/WebUI/Controllers/ProductsController.cs
using System;
using System.Linq;
using Application.client;
using Microsoft.AspNetCore.Mvc;
using WebUI.Models;
using ProductManager = Application.admin.ProductManager;

namespace WebUI.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ProductManager _productManager;
        private readonly Application.client.ProductManager _clientProductManager;
        private readonly WishlistManager _wishlistManager;
        private int TotalProdukte { get; }

        public ProductsController(ProductManager productManager,
            Application.client.ProductManager clientProductManager,WishlistManager wishlistManager)
        {
            _productManager = productManager;
            _clientProductManager = clientProductManager;
            _wishlistManager = wishlistManager;
            TotalProdukte = _productManager.GetProducts().Count();
        }
        
        [HttpGet]
        public IActionResult Index()
        {
            var model = _productManager.GetProducts();
            ViewBag.TotalProdukte = TotalProdukte;
            ViewBag.Produktet = model.Count();
            return View(model);
        }

        [HttpGet]
        [Route("/products/{categorySlug}")]
        public IActionResult FilterProductsByCategories(string categorySlug)
        {
            var products = _clientProductManager.GetProductsByCategory(categorySlug);
            ViewBag.TotalProdukte = TotalProdukte;
            ViewBag.Produktet = products.Count();
            return View("~/Views/Products/Index.cshtml",products);
        }

        [HttpGet]
        public IActionResult FilterProductsByPrice(string startingPrice, string endingPrice)
        {
            var products =
                _clientProductManager.GetProductsByPrice(decimal.Parse(startingPrice), decimal.Parse(endingPrice));
            ViewBag.TotalProdukte = TotalProdukte;
            ViewBag.Produktet = products.Count();
            return View("~/Views/Products/Index.cshtml", products);
        }

        [HttpGet]
        public IActionResult Sort(string type)
        {
            var products = _clientProductManager.SortProducts(type);
            ViewBag.TotalProdukte = TotalProdukte;
            ViewBag.Produktet = products.Count();
            return View("~/Views/Products/Index.cshtml",products);
        }

        
        [HttpGet]
        [Route("/product/{slug}")]
        public IActionResult Product(string slug)
        {
            ViewBag.IsInWishList = false;
            if (User.Identity?.IsAuthenticated != null && User.Identity.IsAuthenticated)
            {
                var customerWishlist = _wishlistManager.GetWishlistForCustomer(Convert.ToInt32(User.Claims.ElementAt(1).Value));
                if (customerWishlist.Any(x=>x.Product.Slug == slug))
                {
                    ViewBag.IsInWishList = true;
                }
            }
            var product = _productManager.GetProductBySlug(slug);
            if (product == null)
            {
                return RedirectToAction("Index","Home");
            }
            var productCategory = product.ProductCategories.FirstOrDefault()!.CategoryId;
            var relatedProduct = _clientProductManager.GetRelatedProducts(productCategory).ToList();
            relatedProduct.RemoveAll(x => x.ProductId == product.ProductId);
            var productDetailModel = new ProductDetailsViewModel
            {
                Product = product,
                RelatedProducts = relatedProduct.Distinct().AsEnumerable()
            };
            return View("ProductDetails",productDetailModel);
        }
    }
}

src/WebUI/Views/Cart/Index.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer _localizer
@{
    ViewBag.Title = "Shporta";
    Layout = "_Layout";
    var cart = ViewBag.Cart as List<Cart>;
}


@if (cart == null || !cart!.Any())
{
    <div class="text-center d-flex justify-content-center align-items-center mtb-100">
        <h4 class="alert alert-info" style="width: 500px">@_localizer["shportaZbrazet"]</h4>
    </div>
}
else
{
<div class="cart-main-area pt-85 pb-90">
    <div class="container">
        <h3 class="cart-page-title">@_localizer["artikujtShportes"]</h3>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                <div class="table-content table-responsive cart-table-content">
                    <table>
                        <thead>
                            <tr>
                                <th>@_localizer["foto"]</th>
                                <th>@_localizer["emriProduktit"]</th>
                                <th>@_localizer["cmimi"]</th>
                                <th>@_localizer["sasia"]</th>
                                <th>@_localizer["subtotali"]</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in cart)
                            {
                                <tr>
                                    <td class="product-thumbnail">
                                        <a asp-controller="Products" asp-action="Product" asp-route-slug="@item.Product.Slug">
                                            <img src="@item.Product.ProductGalleries.FirstOrDefault()?.URL" style="width: 80px;height: 80px;object-fit: contain" alt="product">
                                        </a>
                                    </td>
                                    <td class="product-name">
                                        <a asp-controller="Products" asp-action="Product" asp-route-slug="@item.Product.Slug">@(item.Product.Name[..30])...</a>
                                    </td>
                                    <td class="product-price-cart">
                                        <span class="amount">@item.Product.Price.ToString("#,##0.00") €</span>
                                    </td>
                                    <td class="product-quantity">
                                        <div class="cart-plus-minus">
                                            <input readonly="readonly" class="cart-plus-minus-box" type="text" name="qtybutton" value="@item.Quantity">
                                        </div>
                                    </td>
                                    @{
                                        var subtotal = item.Product.Price * item.Quantity;
                                    }
                                    <td class="product-subtotal">@subtotal.ToString("#,##0.00") €</td>
                                    <td class="product-remove">
                                        <form id="delete-product" asp-controller="Cart" asp-action="Remove" asp-route-id="@item.Product.ProductId">
                                            <a onclick='document.getElementById("delete-product").submit();'><i class="la la-close"></i></a>
                                        </form>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="cart-shiping-update-wrapper">
                            <div class="cart-shiping-update">
                                <a asp-controller="Home" asp-action="Index">@_localizer["vazhdoniBlerje"]</a>
                            </div>
                            <div class="cart-clear">
                                <button>@_localizer["perditsoShporten"]</button>
                                <a asp-action="Clear">@_localizer["pastroShporten"]</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4 col-md-6">
                        <div class="cart-tax">
                            <div class="title-wrap">
                                <h4 class="cart-bottom-title section-bg-gray">@_localizer["vleresimiTransportit"]</h4>
                            </div>
                            <div class="tax-wrapper">
                                <p>@_localizer["destinacioni"]</p>
                                <div class="tax-select-wrapper">
                                    <div class="tax-select">
                                        <label>
                                            * @_localizer["shteti"]
                                        </label>
                                        <select class="email s-email s-wid">
                                            <option>Kosovë</option>
                                            <option>Shqipëri</option>
                                            <option>Maqedoni</option>
                                            <option>Diasporë</option>
                                        </select>
                                    </div>
                                    <div class="tax-select">
                                        <label>
                                            * @_localizer["kodiPostal"]
                                        </label>
                                        <input type="text">
                                    </div>
                                    <button class="cart-btn-2" type="submit">@_localizer["kalkulo"]</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="discount-code-wrapper">
                            <div class="title-wrap">
                                <h4 class="cart-bottom-title section-bg-gray">@_localizer["perdorKodin"]</h4>
                            </div>
                            <div class="discount-code">
                                <p>@_localizer["futKodin"]</p>
                                <form>
                                    <input type="text" required="" name="name">
                                    <button class="cart-btn-2" type="submit">@_localizer["aplikoKodin"]</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-12">
                        <div class="grand-totall">
                            <div class="title-wrap">
                                <h4 class="cart-bottom-title section-bg-gary-cart">@_localizer["totali"]</h4>
                            </div>
                            @{
                                var subtot = cart.Sum(x => x.Product.Price * x.Quantity);
                                var tot = subtot + 5;
                            }
                            <h5>@_localizer["totalProdukte"] <span>@subtot.ToString("#,##0.00") €</span></h5>
                            <div class="total-shipping">
                                <h5>@_localizer["totalTransporti"]</h5>
                                <ul>
                                    <li><input type="radio" checked="checked" name="shipping"> Standart <span>5 €</span></li>
                                </ul>
                            </div>
                            <h4 class="grand-totall-title">Totali <span>@tot.ToString("#,##0.00") €</span></h4>
                            <a asp-controller="Checkout">@_localizer["vazhdo"]</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
}