src/WebUI/Areas/admin/Controllers/CustomersController.cs
using System.Linq;
using Application.admin;
using Application.client;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebUI.Areas.admin.Controllers
{
    [Area("admin")]
    [Authorize(AuthenticationSchemes = "Admin_Schema")]
    public class CustomersController : Controller
    {
        private readonly CustomerManager _customerManager;
        private readonly OrderService _orderService;

        public CustomersController(CustomerManager customerManager,OrderService orderService)
        {
            _customerManager = customerManager;
            _orderService = orderService;
        }
        
        public IActionResult Index()
        {
            var customers = _customerManager.GetCustomers();
            return View(customers);
        }

        [HttpGet]
        [Route("/admin/customer/{customerId:int}")]
        public IActionResult Details(int customerId)
        {
            var customer = _customerManager.GetCustomer(customerId);
            if (customer == null) return RedirectToAction(nameof(Index));
            customer.Orders = _orderService.GetCustomerOrders(customerId).ToList();
            ViewBag.CustomerMetaData = _customerManager.LastOrderHrs(customerId);
            return View(customer);
        }
    }
}

src/WebUI/Areas/admin/Controllers/OrdersController.cs
using Application.admin;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rotativa.AspNetCore;

namespace WebUI.Areas.admin.Controllers
{
    [Area("admin")]
    [Authorize(AuthenticationSchemes = "Admin_Schema")]
    public class OrdersController : Controller
    {
        private readonly OrderManager _orderManager;

        public OrdersController(OrderManager orderManager)
        {
            _orderManager = orderManager;
        }
        
        public IActionResult Index()
        {
            var orders = _orderManager.GetOrders();
            return View(orders);
        }

        [HttpGet]
        public IActionResult Details(string orderNumber)
        {
            var order = _orderManager.GetOrderDetails(orderNumber);
            return View(order);
        }

        [HttpGet]
        public IActionResult Print(string orderNumber)
        {
            var order = _orderManager.GetOrderDetails(orderNumber);
            return View(order);
        }

        [HttpPost]
        public IActionResult ChangeOrderStatus(string orderNumber,int orderStatus)
        {
            var result = _orderManager.UpdateOrderStatus(orderNumber, orderStatus);
            return Json(result);
        }
    }
}

src/WebUI/Areas/admin/Views/Customers/Details.cshtml
@using Humanizer
@using Data.admin
@using Domain.Enums
@model Domain.Entities.Customer

@{
    ViewBag.Title = "Details";
    Layout = "_AdminLayout";
    var customerMeta = ViewBag.CustomerMetaData as CustomerOrderMetaData;
}

<div id="top" class="sa-app__body">
   <div class="mx-sm-2 px-2 px-sm-3 px-xxl-4 pb-6">
      <div class="container container--max--xl">
         <div class="py-5">
            <div class="row g-4 align-items-center">
               <div class="col">
                  <nav class="mb-2" aria-label="breadcrumb">
                     <ol class="breadcrumb breadcrumb-sa-simple">
                        <li>
                           <a style="margin-right: 10px" asp-controller="Dashboard" asp-action="Index">Ballina</a>
                        </li>
                        <li>
                           <a style="margin-right: 10px" asp-controller="Customers" asp-action="Index">Konsumatorët</a>
                        </li>
                        <li aria-current="page">@Model.FullName</li>
                     </ol>
                  </nav>
                  <h1 class="h3 m-0">@Model.FullName</h1>
               </div>
               <div class="col-auto d-flex"><a href="#" class="btn btn-secondary me-3">Fshi</a>
                  <a href="#" class="btn btn-primary">Edito</a></div>
            </div>
         </div>
         <div class="sa-entity-layout" data-sa-container-query="{&quot;920&quot;:&quot;sa-entity-layout--size--md&quot;}">
            <div class="sa-entity-layout__body">
               <div class="sa-entity-layout__sidebar">
                  <div class="card">
                     <div class="card-body d-flex flex-column align-items-center">
                        <div class="pt-3">
                           <div class="sa-symbol sa-symbol--shape--circle" style="--sa-symbol--size:6rem"><img src="~/Admin/images/customers/customer-1-64x64.jpg" width="96" height="96" alt=""/></div>
                        </div>
                        <div class="text-center mt-4">
                           <div class="fs-exact-16 fw-medium">@Model.FullName</div>
                           <div class="fs-exact-13 text-muted">
                              <div class="mt-1"><a href="#">@Model.Email</a></div>
                              <div class="mt-1">@Model.Phone</div>
                           </div>
                        </div>
                        <div class="sa-divider my-5"></div>
                        <div class="w-100">
                           <dl class="list-unstyled m-0">
                              <dt class="fs-exact-14 fw-medium">Porosia fundit</dt>
                              <dd class="fs-exact-13 text-muted mb-0 mt-1">
                                 @if (customerMeta.Hours == 0 || customerMeta.OrderNumber == null)
                                 {
                                    <p>Nuk ka porosi</p>
                                 }
                                 else
                                 {
                                    @Model.Orders.OrderByDescending(x=>x.OrderDate).FirstOrDefault().OrderDate.Humanize()
                                 } – <a asp-controller="Orders" asp-action="Details" asp-route-orderNumber="@customerMeta.OrderNumber">#@customerMeta.OrderNumber</a>
                              </dd>
                           </dl>
                           <dl class="list-unstyled m-0 mt-4">
                              <dt class="fs-exact-14 fw-medium">Vlera mesatare e porosive</dt>
                              <dd class="fs-exact-13 text-muted mb-0 mt-1">
                                 @if (Model.Orders.Count > 0)
                                 {
                                    <p>@(Model.Orders.Where(x=>x.Status != OrderStatus.Cancelled).Average(x => x.Total).ToString("#,##0.00")) €</p>
                                 }
                                 else
                                 {
                                    <p>0 €</p>
                                 }
                              </dd>
                           </dl>
                           <dl class="list-unstyled m-0 mt-4">
                              <dt class="fs-exact-14 fw-medium">Regjistruar</dt>
                              <dd class="fs-exact-13 text-muted mb-0 mt-1">@Model.InsertDate.Humanize()</dd>
                           </dl>
                           <dl class="list-unstyled m-0 mt-4">
                              <dt class="fs-exact-14 fw-medium">Email Marketing</dt>
                              <dd class="fs-exact-13 text-muted mb-0 mt-1">Subscribed</dd>
                           </dl>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="sa-entity-layout__main">
                  <div class="sa-card-area">
                     <textarea class="sa-card-area__area" rows="2" placeholder="Shënime rreth konsumatorit"></textarea>
                     <div class="sa-card-area__card">
                        <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit">
                           <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
                           <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
                        </svg>
                     </div>
                  </div>
                  <div class="card mt-5">
                     <div class="card-body px-5 py-4 d-flex align-items-center justify-content-between">
                        <h2 class="mb-0 fs-exact-18 me-4">Porositë</h2>
                        <div class="text-muted fs-exact-14 text-end">Totali i shpenzuar @Model.Orders.Where(x=>x.Status != OrderStatus.Cancelled).Sum(x=>x.Total).ToString("#,##0.00") € në @Model.Orders.Count porosi</div>
                     </div>
                     <div class="table-responsive">
                        <table class="sa-table text-nowrap">
                           <tbody>
                              @foreach (var order in Model.Orders.Take(4))
                              {
                                 <tr>
                                    <td><a asp-controller="Orders" asp-action="Details" asp-route-orderNumber="@order.OrderNumber">#@order.OrderNumber</a></td>
                                    <td>@order.OrderDate.ToString("d")</td>
                                    <td>
                                    @{
                                       await Html.RenderPartialAsync("_OrderStatus", new {order.Status});
                                    }
                                    </td>
                                    <td>@order.OrderDetails.Count() produkte</td>
                                    <td>@order.Total.ToString("#,##0.00") €</td>
                                 </tr>
                              }
                           </tbody>
                        </table>
                     </div>
                     <div class="sa-divider"></div>
                     @if (Model.Orders.Count > 4)
                     {
                        <div class="px-5 py-4 text-center"><a asp-controller="Orders" asp-action="Index">Shiko të gjitha @Model.Orders.Count porosi</a></div>
                     }
                  </div>
                  <div class="card mt-5">
                     <div class="card-body px-5 py-4 d-flex align-items-center justify-content-between">
                        <h2 class="mb-0 fs-exact-18 me-4">Adresat</h2>
                     </div>
                     <div class="sa-divider"></div>
                     <div class="px-5 py-3 my-2 d-flex align-items-center justify-content-between">
                        <div>
                           <div>@Model.FullName</div>
                           <div class="text-muted fs-exact-14 mt-1">@Model.Address @Model.PostalCode, @Model.Country @Model.City, @Model.Email</div>
                        </div>
                        <div>
                           <div class="dropdown">
                              <button class="btn btn-sa-muted btn-sm" type="button" id="address-context-menu-0" data-bs-toggle="dropdown" aria-expanded="false" aria-label="More">
                                 <svg xmlns="http://www.w3.org/2000/svg" width="3" height="13" fill="currentColor">
                                    <path d="M1.5,8C0.7,8,0,7.3,0,6.5S0.7,5,1.5,5S3,5.7,3,6.5S2.3,8,1.5,8z M1.5,3C0.7,3,0,2.3,0,1.5S0.7,0,1.5,0 S3,0.7,3,1.5S2.3,3,1.5,3z M1.5,10C2.3,10,3,10.7,3,11.5S2.3,13,1.5,13S0,12.3,0,11.5S0.7,10,1.5,10z"></path>
                                 </svg>
                              </button>
                              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="address-context-menu-0">
                                 <li><a class="dropdown-item" href="#">Shiko</a></li>
                                 <li>
                                    <hr class="dropdown-divider"/>
                                 </li>
                                 <li><a class="dropdown-item text-danger" href="#">Fshi</a></li>
                              </ul>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

src/WebUI/Areas/admin/Views/Customers/Index.cshtml
@model IEnumerable<Domain.Entities.Customer>
@{
    ViewBag.Title = "Konsumatorët";
    Layout = "_AdminLayout";
}

<div id="top" class="sa-app__body">
   <div class="mx-sm-2 px-2 px-sm-3 px-xxl-4 pb-6">
      <div class="container">
         <div class="py-5">
            <div class="row g-4 align-items-center">
               <div class="col">
                  <nav class="mb-2" aria-label="breadcrumb">
                     <ol class="breadcrumb breadcrumb-sa-simple">
                        <li>
                           <a style="margin-right: 10px" asp-controller="Dashboard" asp-action="Index">Ballina</a>
                        </li>
                        <li aria-current="page">Konsumatorët</li>
                     </ol>
                  </nav>
                  <h1 class="h3 m-0">Konsumatorët</h1>
               </div>
            </div>
         </div>
         <div class="card">
            <div class="p-4"><input type="text" placeholder="Start typing to search for customers" class="form-control form-control--search mx-auto" id="table-search"/></div>
            <div class="sa-divider"></div>
            <table class="sa-datatables-init" data-order="[[ 1, &quot;asc&quot; ]]" data-sa-search-input="#table-search">
               <thead>
                  <tr>
                     <th class="w-min" data-orderable="false"><input type="checkbox" class="form-check-input m-0 fs-exact-16 d-block" aria-label="..."/></th>
                     <th class="min-w-20x">Emri</th>
                     <th>Regjistuar</th>
                     <th>Shteti</th>
                     <th>Porositë</th>
                     <th>Shpenzuar</th>
                     <th class="w-min" data-orderable="false"></th>
                  </tr>
               </thead>
               <tbody>
                  @foreach (var customer in Model)
                  {
                     <tr>
                     <td><input type="checkbox" class="form-check-input m-0 fs-exact-16 d-block" aria-label="..."/></td>
                     <td>
                        <div class="d-flex align-items-center">
                           <a asp-controller="Customers" asp-action="Details" asp-route-customerId="@customer.CustomerId" class="me-4">
                              <div class="sa-symbol sa-symbol--shape--rounded sa-symbol--size--lg">
                                 <img src="~/Admin/images/customers/customer.png" style="width: 20px;object-fit: contain;" alt=""/>
                              </div>
                           </a>
                           <div>
                              <a asp-controller="Customers" asp-action="Details" asp-route-customerId="@customer.CustomerId" class="text-reset">@customer.Name @customer.Surname</a>
                              <div class="text-muted mt-n1">@customer.Email</div>
                           </div>
                        </div>
                     </td>
                     <td class="text-nowrap">@customer.InsertDate</td>
                     <td>@customer.Country</td>
                     <td>@customer.City</td>
                        <td>
                           @if (customer.Total.HasValue)
                           {
                              var ordTotal = (decimal) customer.Total;
                              <div class="sa-price"><span class="sa-price__integer">@ordTotal.ToString("#,##0.00") €</span></div>
                           }
                           else
                           {
                              <div class="sa-price"><span class="sa-price__integer">0 €</span></div> 
                           }
                        </td>
                     <td>
                        <div class="dropdown">
                           <button class="btn btn-sa-muted btn-sm" type="button" id="customer-context-menu-0" data-bs-toggle="dropdown" aria-expanded="false" aria-label="More">
                              <svg xmlns="http://www.w3.org/2000/svg" width="3" height="13" fill="currentColor">
                                 <path d="M1.5,8C0.7,8,0,7.3,0,6.5S0.7,5,1.5,5S3,5.7,3,6.5S2.3,8,1.5,8z M1.5,3C0.7,3,0,2.3,0,1.5S0.7,0,1.5,0 S3,0.7,3,1.5S2.3,3,1.5,3z M1.5,10C2.3,10,3,10.7,3,11.5S2.3,13,1.5,13S0,12.3,0,11.5S0.7,10,1.5,10z"></path>
                              </svg>
                           </button>
                           <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="customer-context-menu-0">
                              <li><a class="dropdown-item" href="#">Edit</a></li>
                              <li>
                                 <hr class="dropdown-divider"/>
                              </li>
                              <li><a class="dropdown-item text-danger" href="#">Delete</a></li>
                           </ul>
                        </div>
                     </td>
                  </tr>
                  }
               </tbody>
            </table>
         </div>
      </div>
   </div>
</div>